spring:
  datasource:
    username: postgres
    password: 12345
    url: jdbc:postgresql://localhost:5432/bank
  main:
    allow-bean-definition-overriding: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      temp:
        use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: update
    show-sql: true
  spring:
    resources:
      add-mappings=true:
